[general]
import = [
"~/.config/alacritty/tokyonight-moon.toml",
]

[env]
TERM = "xterm-256color"

[window]
# Start maximized or in fullscreen
decorations = "full"
startup_mode = "Maximized"
dynamic_padding = true
opacity = 0.95
padding = { x = 10, y = 10 }

[font]
normal = { family = "Monospace", style = "Regular" }
bold = { family = "Monospace", style = "Bold" }
italic = { family = "Monospace", style = "Italic" }
size = 13.0

[cursor]
style = { shape = "Beam", blinking = "Off" }
unfocused_hollow = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
